### PR TITLE
fix(docs): spacing

### PR DESCRIPTION
**Pull request by mesqueeb**

### CODE REVIEW

**Comment by robingenz** [comment]
This time the spacing is correct 😄

**Comment by mesqueeb** [comment]
@robingenz It is? :O 

This is what my actual PodFile looks like
image

This is what the markdown looks currently:
image

This is what the PR looks like:

image

Do you think it's better without the indentation?

**Comment by robingenz** [comment]
Excuse me! You are right. Thank you for checking again. 😄

**Comment by mesqueeb** [comment]
@robingenz no worries! Glad to help ;)

**Pull request merged**
